# Generated by Django 3.0.9 on 2020-08-18 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('led_colors', '0003_auto_20200818_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.BinaryField(default=b'', editable=True, max_length=32)),
                ('function', models.TextField(blank=True, null=True)),
                ('period_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='current_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='led_colors.ColorProfile'),
        ),
    ]
