# Generated by Django 3.1 on 2020-08-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led_colors', '0004_auto_20200818_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorprofile',
            name='color',
            field=models.CharField(default='ffffffff', max_length=8),
        ),
    ]
