# Generated by Django 3.1 on 2020-08-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led_colors', '0005_auto_20200820_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorprofile',
            name='name',
            field=models.CharField(default='nonamer', max_length=32),
            preserve_default=False,
        ),
    ]
