# Generated by Django 3.1 on 2020-08-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led_colors', '0006_colorprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='on',
            field=models.BooleanField(default=False),
        ),
    ]
